# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4eb13882a7eae642f18ba97289357aae4271fb864a380d1aefed212cd84368b4632b98f532d67c33cfc709cc1583343ca28fef5f742a30378e53a39fa9f4d407

test:
  secret_key_base: d6b4ebd7b3953655953fb0ad4d7481b03ea4424f3d2e56bae65e85f84811af34201df6cf428326f3d40fb29bb3c43f7dfec848eeadd19a0e1f3c5b9c43e277d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
